### ISSUE TITLE
Dimensions must be equal, but are 2 and 0 for '{{node mul_1}} = Mul[T=DT_FLOAT](Exp, mul_1/y)' with input shapes: [32,20,20,3,2], [0].

### ISSUE THREAD

**Issue by Michelangelo-Y** [jahongir7174/YOLOv5-tf#18]
Traceback (most recent call last):
  File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 280, in <module>
    train()
  File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 91, in train
    train_fn()
  File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 84, in train_fn
    loss = distributed_train_step(image, y_true)
  File "/usr/local/python3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/python3/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 69, in distributed_train_step  *
        per_replica_losses = strategy.run(train_step, args=(image, y_true))
    File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 60, in train_step  *
        loss = compute_loss(y_true, y_pred)
    File "/home/x/PycharmProjects/YOLOv5-tf-master/main.py", line 53, in compute_loss  *
        total_loss = loss_object(y_pred, y_true)
    File "/home/x/PycharmProjects/YOLOv5-tf-master/nets/nn.py", line 271, in __call__  *
        loss += self.compute_loss(y_pred[i], y_true[i], anchor_group[i])
    File "/home/x/PycharmProjects/YOLOv5-tf-master/nets/nn.py", line 217, in compute_loss  *
        x_y_offset, pred_boxes, pred_conf, pred_prob = process_layer(y_pred, anchors)
    File "/home/x/PycharmProjects/YOLOv5-tf-master/nets/nn.py", line 130, in process_layer  *
        box_sizes = tf.exp(box_sizes) * rescaled_anchors

    ValueError: Dimensions must be equal, but are 2 and 0 for '{{node mul_1}} = Mul[T=DT_FLOAT](Exp, mul_1/y)' with input shapes: [32,20,20,3,2], [0].

**Comment by Michelangelo-Y** [comment]
my config:
import os
import numpy

width = [0.50, 0.75, 1.0, 1.25]
depth = [0.33, 0.67, 1.0, 1.33]

versions = ['s', 'm', 'l', 'x']
data_dir = os.path.join('/home/x/', 'save', 'yolov5_data')

threshold = 0.3
max_boxes = 150
image_dir = 'images'
label_dir = 'labels'

num_epochs = 300
batch_size = 32
image_size = 640
class_dict = {'tree': 0, 'house': 1, 'uav': 2, 'tower': 3}

version = 'l'
anchors = numpy.array([[99., 67.], [208., 314.], [331., 650.], [699., 436.]], numpy.float32)

**Comment by Michelangelo-Y** [comment]
i have found the error below,but how to  fix it?
nn.py line 269:
anchor_group = [config.anchors[6:9], config.anchors[3:6], config.anchors[0:3]]

anchors = numpy.array([[99., 67.], [208., 314.], [331., 650.], [699., 436.]], numpy.float32)

**Comment by jahongir7174** [comment]
please see the original [anchors](https://github.com/jahongir7174/YOLOv5-tf/blob/ea02a297b39b902fe535eda1a87997a2f7db1419/utils/config.py#L32)
