### ISSUE TITLE
Can't generate anchors

### ISSUE THREAD

**Issue by masc-it** [jahongir7174/YOLOv5-tf#5]
I'm trying to train my dataset using this repo, but I'm facing errors in the anchors generating process:

```D:\Projects\python\YOLOv5_2>python generate.py
Traceback (most recent call last):
  File "generate.py", line 84, in <module>
    generator.generate_anchor()
  File "generate.py", line 59, in generate_anchor
    boxes = self.get_boxes()
  File "generate.py", line 73, in get_boxes
    y_min = annotation[1]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

This is a sample of annotation file (.xml):

```<annotation>
	<folder>train</folder>
	<filename>20201003140922.png</filename>
	<path>D:\Projects\datasets\kings\train\20201003140922.png</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>800</width>
		<height>600</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>king</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>202</xmin>
			<ymin>216</ymin>
			<xmax>469</xmax>
			<ymax>527</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by jahongir7174** [comment]
I fixed the issue, load_label function returns boxes and labels, we need only boxes

**Comment by jahongir7174** [comment]
I am closing the issue. if you have any issue, you can open again
